<?php
/**
 * Test configuration — auto-generated by tests/bootstrap.php.
 * Uses SQLite in-memory so tests run without MySQL.
 */

// ── Database (SQLite in-memory) ────────────────────────────────────
if (!defined('DB_HOST')) define('DB_HOST', 'sqlite');
if (!defined('DB_NAME')) define('DB_NAME', ':memory:');
if (!defined('DB_USER')) define('DB_USER', '');
if (!defined('DB_PASS')) define('DB_PASS', '');

// ── Email / SMTP ────────────────────────────────────────────────────
if (!defined('SMTP_HOST'))   define('SMTP_HOST',   '127.0.0.1');
if (!defined('SMTP_PORT'))   define('SMTP_PORT',   25);
if (!defined('SMTP_FROM'))   define('SMTP_FROM',   'test@zineexchangeclub.test');
if (!defined('SMTP_FROM_NAME')) define('SMTP_FROM_NAME', 'Test Zine Exchange');

// ── Site ────────────────────────────────────────────────────────────
if (!defined('SITE_URL'))     define('SITE_URL',     'http://test.local');
if (!defined('SITE_TITLE'))   define('SITE_TITLE',   'Test Zine Exchange Club');
if (!defined('CONTENT_TYPE')) define('CONTENT_TYPE', 'zine');

// ── Admin ───────────────────────────────────────────────────────────
if (!defined('ADMIN_EMAIL')) define('ADMIN_EMAIL', 'admin@zineexchangeclub.test');

// ── Pairing ─────────────────────────────────────────────────────────
if (!defined('PAIRING_ALGORITHM')) define('PAIRING_ALGORITHM', 'random');

// ── Captcha ─────────────────────────────────────────────────────────
if (!defined('CAPTCHA_MAX_RETRIES')) define('CAPTCHA_MAX_RETRIES', 3);

// ── Session (safe for CLI) ──────────────────────────────────────────
if (session_status() === PHP_SESSION_NONE) {
    ini_set('session.use_cookies', '0');
    ini_set('session.use_only_cookies', '0');
    session_start();
}

// ── Database connection (SQLite) ────────────────────────────────────
if (!function_exists('getDB')) {
    function getDB() {
        static $pdo = null;
        if ($pdo === null) {
            $pdo = new PDO('sqlite::memory:', null, null, [
                PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES   => false,
            ]);
        }
        return $pdo;
    }
}