<?php
/**
 * Test Bootstrap — shared infrastructure for all Zine Exchange Club tests.
 *
 * 1. Defines assertion helpers (assert_equal, assert_true, assert_throws)
 * 2. Creates a test config.php (SQLite in-memory) in the project root
 *    IF none exists yet (config.php is in .gitignore, so this is safe).
 * 3. Provides createTestSchema() for DB-dependent tests.
 * 4. Starts a session for CLI test runners.
 */

// ── Assertion helpers ───────────────────────────────────────────────

function assert_equal(string $label, mixed $expected, mixed $actual): void {
    if ($expected === $actual) {
        echo "[PASS] {$label}\n";
    } else {
        $exp = var_export($expected, true);
        $got = var_export($actual, true);
        echo "[FAIL] {$label} -- expected {$exp} got {$got}\n";
    }
}

function assert_true(string $label, bool $result): void {
    echo ($result ? "[PASS]" : "[FAIL]") . " {$label}\n";
}

function assert_throws(string $label, callable $fn, string $exceptionClass = \Throwable::class): void {
    try {
        $fn();
        echo "[FAIL] {$label} -- no exception was thrown\n";
    } catch (\Throwable $e) {
        if ($e instanceof $exceptionClass) {
            echo "[PASS] {$label}\n";
        } else {
            echo "[FAIL] {$label} -- expected {$exceptionClass} got " . get_class($e) . "\n";
        }
    }
}

// ── Ensure a test config.php exists ────────────────────────────────

$configPath = __DIR__ . '/../config.php';

if (!file_exists($configPath)) {
    $testConfig = <<<'PHP'
<?php
/**
 * Test configuration — auto-generated by tests/bootstrap.php.
 * Uses SQLite in-memory so tests run without MySQL.
 */

// ── Database (SQLite in-memory) ────────────────────────────────────
if (!defined('DB_HOST')) define('DB_HOST', 'sqlite');
if (!defined('DB_NAME')) define('DB_NAME', ':memory:');
if (!defined('DB_USER')) define('DB_USER', '');
if (!defined('DB_PASS')) define('DB_PASS', '');

// ── Email / SMTP ────────────────────────────────────────────────────
if (!defined('SMTP_HOST'))   define('SMTP_HOST',   '127.0.0.1');
if (!defined('SMTP_PORT'))   define('SMTP_PORT',   25);
if (!defined('SMTP_FROM'))   define('SMTP_FROM',   'test@zineexchangeclub.test');
if (!defined('SMTP_FROM_NAME')) define('SMTP_FROM_NAME', 'Test Zine Exchange');

// ── Site ────────────────────────────────────────────────────────────
if (!defined('SITE_URL'))     define('SITE_URL',     'http://test.local');
if (!defined('SITE_TITLE'))   define('SITE_TITLE',   'Test Zine Exchange Club');
if (!defined('CONTENT_TYPE')) define('CONTENT_TYPE', 'zine');

// ── Admin ───────────────────────────────────────────────────────────
if (!defined('ADMIN_EMAIL')) define('ADMIN_EMAIL', 'admin@zineexchangeclub.test');

// ── Pairing ─────────────────────────────────────────────────────────
if (!defined('PAIRING_ALGORITHM')) define('PAIRING_ALGORITHM', 'random');

// ── Captcha ─────────────────────────────────────────────────────────
if (!defined('CAPTCHA_MAX_RETRIES')) define('CAPTCHA_MAX_RETRIES', 3);

// ── Session (safe for CLI) ──────────────────────────────────────────
if (session_status() === PHP_SESSION_NONE) {
    ini_set('session.use_cookies', '0');
    ini_set('session.use_only_cookies', '0');
    session_start();
}

// ── Database connection (SQLite) ────────────────────────────────────
if (!function_exists('getDB')) {
    function getDB() {
        static $pdo = null;
        if ($pdo === null) {
            $pdo = new PDO('sqlite::memory:', null, null, [
                PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES   => false,
            ]);
        }
        return $pdo;
    }
}
PHP;
    file_put_contents($configPath, $testConfig);
}

// ── Schema creation helper ──────────────────────────────────────────

/**
 * Create the full test schema on the given PDO connection (SQLite).
 * Call this at the top of every DB-dependent test file.
 */
function createTestSchema(PDO $db): void {
    $db->exec("
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            email TEXT NOT NULL UNIQUE,
            password TEXT NOT NULL,
            postal_address TEXT NOT NULL,
            accepts_adult_zines INTEGER DEFAULT 0,
            country TEXT NOT NULL,
            is_admin INTEGER DEFAULT 0,
            email_confirmed INTEGER DEFAULT 0,
            email_confirmation_token TEXT,
            email_token_expires TEXT,
            password_reset_token TEXT,
            password_reset_expires TEXT,
            created_at TEXT DEFAULT (datetime('now')),
            updated_at TEXT DEFAULT (datetime('now'))
        )
    ");

    $db->exec("
        CREATE TABLE IF NOT EXISTS zines (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            theme TEXT,
            format TEXT,
            created_at TEXT DEFAULT (datetime('now')),
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )
    ");

    $db->exec("
        CREATE TABLE IF NOT EXISTS cycles (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            start_date TEXT NOT NULL,
            registration_open INTEGER DEFAULT 1,
            pairing_done INTEGER DEFAULT 0,
            status TEXT DEFAULT 'active',
            created_at TEXT DEFAULT (datetime('now'))
        )
    ");

    $db->exec("
        CREATE TABLE IF NOT EXISTS cycle_participations (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            cycle_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            wants_to_participate INTEGER DEFAULT 1,
            participation_confirmed INTEGER DEFAULT 0,
            pairing_confirmed INTEGER DEFAULT 0,
            paired_with_id INTEGER,
            zine_sent INTEGER DEFAULT 0,
            zine_sent_date TEXT,
            zine_received INTEGER DEFAULT 0,
            zine_received_date TEXT,
            confirmation_token TEXT,
            confirmation_token_expires TEXT,
            created_at TEXT DEFAULT (datetime('now')),
            updated_at TEXT DEFAULT (datetime('now')),
            FOREIGN KEY (cycle_id) REFERENCES cycles(id) ON DELETE CASCADE,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
            FOREIGN KEY (paired_with_id) REFERENCES users(id) ON DELETE SET NULL,
            UNIQUE (cycle_id, user_id)
        )
    ");

    $db->exec("
        CREATE TABLE IF NOT EXISTS cycle_pairings (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            cycle_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            partner_id INTEGER NOT NULL,
            pairing_confirmed INTEGER DEFAULT 0,
            confirmation_token TEXT,
            confirmation_token_expires TEXT,
            zine_sent INTEGER DEFAULT 0,
            zine_sent_date TEXT,
            zine_received INTEGER DEFAULT 0,
            zine_received_date TEXT,
            created_at TEXT DEFAULT (datetime('now')),
            FOREIGN KEY (cycle_id) REFERENCES cycles(id) ON DELETE CASCADE,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
            FOREIGN KEY (partner_id) REFERENCES users(id) ON DELETE CASCADE
        )
    ");

    $db->exec("
        CREATE TABLE IF NOT EXISTS email_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER,
            cycle_id INTEGER,
            email_type TEXT NOT NULL,
            sent_at TEXT DEFAULT (datetime('now')),
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
            FOREIGN KEY (cycle_id) REFERENCES cycles(id) ON DELETE SET NULL
        )
    ");

    $db->exec("
        CREATE TABLE IF NOT EXISTS announcements (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL,
            content TEXT NOT NULL,
            created_at TEXT DEFAULT (datetime('now')),
            updated_at TEXT DEFAULT (datetime('now')),
            created_by INTEGER NOT NULL,
            email_sent INTEGER DEFAULT 0,
            FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
        )
    ");

    $db->exec("
        CREATE TABLE IF NOT EXISTS announcement_views (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            announcement_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            viewed_at TEXT DEFAULT (datetime('now')),
            UNIQUE (announcement_id, user_id),
            FOREIGN KEY (announcement_id) REFERENCES announcements(id) ON DELETE CASCADE,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )
    ");
}

/**
 * Reset session state between tests (clear $_SESSION).
 */
function resetSession(): void {
    $_SESSION = [];
}

/**
 * Insert a test user and return its ID.
 */
function insertTestUser(PDO $db, array $overrides = []): int {
    $defaults = [
        'name'                => 'Test User',
        'email'               => 'test@example.com',
        'password'            => password_hash('secret123', PASSWORD_DEFAULT),
        'postal_address'      => '123 Test St',
        'country'             => 'US',
        'accepts_adult_zines' => 0,
        'is_admin'            => 0,
        'email_confirmed'     => 1,
    ];
    $data = array_merge($defaults, $overrides);

    // Only pass columns that exist in the INSERT query
    $columns = ['name', 'email', 'password', 'postal_address', 'country',
                'accepts_adult_zines', 'is_admin', 'email_confirmed'];
    $filtered = array_intersect_key($data, array_flip($columns));

    $stmt = $db->prepare("
        INSERT INTO users (name, email, password, postal_address, country,
                           accepts_adult_zines, is_admin, email_confirmed)
        VALUES (:name, :email, :password, :postal_address, :country,
                :accepts_adult_zines, :is_admin, :email_confirmed)
    ");
    $stmt->execute($filtered);
    return (int)$db->lastInsertId();
}

/**
 * Insert a test cycle and return its ID.
 */
function insertTestCycle(PDO $db, array $overrides = []): int {
    $defaults = [
        'name'              => 'Test Cycle',
        'start_date'        => date('Y-m-d'),
        'registration_open' => 1,
        'pairing_done'      => 0,
        'status'            => 'active',
    ];
    $data = array_merge($defaults, $overrides);

    $stmt = $db->prepare("
        INSERT INTO cycles (name, start_date, registration_open, pairing_done, status)
        VALUES (:name, :start_date, :registration_open, :pairing_done, :status)
    ");
    $stmt->execute($data);
    return (int)$db->lastInsertId();
}
