<?php
/**
 * Collects line coverage across all test files and reports uncovered lines.
 * Run as: XDEBUG_MODE=coverage php tests/run_coverage.php
 */

if (!extension_loaded('xdebug')) {
    echo "Xdebug not available. Run individual test files instead.\n";
    exit(1);
}

// Roots — source files live in the project root (includes/, admin/, emails/,
// and top-level .php files). The project root is the parent of tests/.
$projectRoot = realpath(__DIR__ . '/..');
$testDir     = __DIR__;

// Directories to exclude from the coverage report
$excludeDirs = [
    realpath($testDir),
    realpath($projectRoot . '/scripts'),
    realpath($projectRoot . '/.serena'),
    realpath($projectRoot . '/.claude'),
];

// Files to exclude by exact path
$excludeFiles = [
    realpath($projectRoot . '/config.php'),         // auto-generated by bootstrap
    realpath($projectRoot . '/config.php.sample'),  // not loaded
];

$excludeFiles = array_filter($excludeFiles);

xdebug_start_code_coverage(XDEBUG_CC_UNUSED | XDEBUG_CC_DEAD_CODE);

// Run every test file
foreach (glob($testDir . '/*Test.php') as $file) {
    include $file;
}

$coverage = xdebug_get_code_coverage();
xdebug_stop_code_coverage();

// Filter to source files only and build report
$report = [];
foreach ($coverage as $file => $lines) {
    $real = realpath($file);
    if ($real === false) continue;

    // Skip files outside the project root
    if (strpos($real, $projectRoot) !== 0) continue;

    // Skip excluded directories
    $skip = false;
    foreach ($excludeDirs as $dir) {
        if ($dir && strpos($real, $dir) === 0) {
            $skip = true;
            break;
        }
    }
    if ($skip) continue;

    // Skip excluded files
    if (in_array($real, $excludeFiles)) continue;

    $missed = [];
    foreach ($lines as $line => $count) {
        if ($count === -1) {
            $missed[] = $line; // executable but not hit
        }
    }
    if ($missed) {
        $report[$real] = $missed;
    }
}

if (empty($report)) {
    echo "\n[COVERAGE] All executable lines in source files were hit.\n";
} else {
    echo "\n[COVERAGE] Uncovered lines:\n";
    foreach ($report as $file => $lines) {
        $short = str_replace($projectRoot . '/', '', $file);
        echo "  {$short}: lines " . implode(', ', array_slice($lines, 0, 40)) . "\n";
        if (count($lines) > 40) {
            echo "    ... and " . (count($lines) - 40) . " more uncovered lines\n";
        }
    }
    echo "\n";
}
